### ISSUE TITLE
Git CMD window popping up

### ISSUE THREAD

**Issue by michalpenka** [ygoe/NetRevisionTask#1]
GIT cmd window keeps popping up while building the solution.

This is very annoying as it gets the user/mouse/keyboard focus, preventing any other work during the build.

**Comment by ygoe** [comment]
Never seen this anywhere. Can you try to isolate the Git configuration that causes this?

**Comment by ygoe** [comment]
I have added some code that might solve your issue. Please re-open with further details if it still affects you.
