### ISSUE TITLE
Unexplained exception

### ISSUE THREAD

**Issue by The-Futurist** [ygoe/NetRevisionTask#13]
Hi,

I've used NetRevisionTool a great deal (I have even customized that and added several useful features).

Today I'm playing around with NetRevisionTask as we move stuff more .NET Core and .NET Standard and I'm getting errors.

For example this:

    <NrtRevisionFormat>{revnum}{branch}{CHASH}</NrtRevisionFormat>

causes the error: Revision ID cannot be truncated to dotted-numeric: 285master28C9767DE9665BB0E0A541DD481F02ED5CB72968

Is this a bug or am I doing something silly?

**Comment by ygoe** [comment]
Can't take a closer look right now, but it looks like this: You provided a version string that does not resolve to a pure numeric version. That string shall be used for all version attributes, including those that can only take numeric versions. Please read the documentation/readme about selecting which attributes to set. You might only want to set the informational version attribute which can accept an arbitrary string, but not the other attributes.

**Comment by The-Futurist** [comment]
@ygoe - HI and thanks for the quick reply.

Let me review what you say and see how that goes, its true I do only want to se the informational version attribute, this is what we did in our .Net Framework code and I'm trying to get the same end result with .Net Core/.Net Standard. Not concerned just yet with version numbers (the commit ID is what we use for now). Trying to get the same end result we currently get using .Net Framework projects with NetRevisionTool, want the end result to be the same.

**Comment by The-Futurist** [comment]
@ygoe - OK that's my issue, the documentation doesn't show how to set the informational version attribute inside the JSON for a .Net Core or .Net Standard project, it only talks about this in the context of pre .Net Core apps where it gives examples using AssemblyInfo.cs.

**Comment by The-Futurist** [comment]
@ygoe 

OK I didn't realize that these attributes were named as they are, so here's what I tried:

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <InformationalVersion>{mname} {cname} {branch} {CHASH:16} {url}</InformationalVersion>
    <!--<NrtRevisionFormat>{semvertag} {revnum} {mname} {cname} {branch} {CHASH:8} {url}</NrtRevisionFormat>-->
    <NrtResolveSimpleAttributes>true</NrtResolveSimpleAttributes>
    <NrtResolveInformationalAttribute>true</NrtResolveInformationalAttribute>
    <NrtResolveCopyright>true</NrtResolveCopyright>
    <NrtTagMatch>v[0-9]*</NrtTagMatch>
    <NrtRemoveTagV>true</NrtRemoveTagV>
    <NrtRequiredVcs>git</NrtRequiredVcs>
    <NrtShowRevision>false</NrtShowRevision>
    <AssemblyVersion>1.2.3.4</AssemblyVersion>
    <FileVersion>1.2.3.4</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Unclassified.NetRevisionTask" Version="0.3.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>
```

And this is the result:

![image](https://user-images.githubusercontent.com/12262952/93916142-e89f6480-fcbd-11ea-8237-89115496b61c.png)

No sign of the {mname} or {cname} in fact that result looks similar to what it did before I commented out the NrtRevisionFormat, as if its now defaulting in some way.

**Comment by The-Futurist** [comment]
FYI we log the assembly's informational version text so our logs tell us the details of the commit, branch and so on when an app logs errors or anything, this is perhaps not the way to work really (tags etc are better) but I'm trying to bring .Net Standard in for our work without breaking current practices for stamping build info onto our assemblies.

We also embed this in the attribute today (that is in AssemblyInfo.cs projects):

`{!:(Warning - There were uncommitted changes present)}`

Is this also supported in NetRevisionTask?

OK I see that it is !

**Comment by ygoe** [comment]
Yes, all the formatting features from NetRevisionTool have been copied to NetRevisionTask. The newer project is just another shell for the same Git/SVN and formatting code.

So I see that you have found the solution and this issue can be closed? Or have I missed an open question?

**Comment by The-Futurist** [comment]
@ygoe - Hi,

No a problem still remains, I cannot get the version string generated as I'd expect, I am confused see this comment above https://github.com/ygoe/NetRevisionTask/issues/13#issuecomment-696865147
Thanks.

**Comment by ygoe** [comment]
Sorry, I don't see any problem here. You didn't specify a revision format, so the default is used. And that leads to exactly the result you showed in the file properties. Everything works as expected and hopefully also as described. If you want a different revision format, you should not comment out that `NrtRevisionFormat` property in the project file.

**Comment by The-Futurist** [comment]
Hi, unfortunately this was so long ago and the original project discontinued that I can no longer recall much about the issue, feel free to close it.
