### ISSUE TITLE
add UWP support

### ISSUE THREAD

**Issue by MagicAndre1981** [ygoe/NetRevisionTask#2]
For UWP apps the version is defined in the `Package.appxmanifest`. 

  <Identity Name="foo" Publisher="CN=bar" Version="Maj.Min.SVNRev.0" />

Can you also provide support for settings this data?

**Comment by ygoe** [comment]
I don't have the UWP tools installed, the Xamarin tools already take enough disk space. ;-) So I don't know what files with which content are there in that project type. Could you provide a Pull Request that adds the requested feature?

**Comment by MagicAndre1981** [comment]
no, I don't want to try to understand your code to add this. I use a PS1 script started after SVN commit/update via TSVN to update the file with the new rev data. In all other projects in the solution I use yours, but want to have 1 single solution to update all version info.

**Comment by MagicAndre1981** [comment]
any update on this? Can you also support android apps (`AndroidManifest.xml`)?

**Comment by ygoe** [comment]
Sorry, no update yet. I still have nothing to do with UWP (and maybe never will) and didn't get to looking into Xamarin for Android (if that's what you mean). Any help would be appreciated here.

**Comment by MagicAndre1981** [comment]
The AndroidManifest.xml has [2 entries which are needed to be updated](https://developer.android.com/studio/publish/versioning):

`android:versionCode` is an integer and is used by android system to determine if this is an update
`android:versionName` is a string which user friendly version number

so an example would be `android:versionCode="101110" android:versionName="1.0.111.0"` and here the 111 would be my code revision from Subversion.

**Comment by ygoe** [comment]
Would you be okay with one of the existing placeholders for `versionCode`, like `{revnum}` or its variants with an offset?

Be aware that concatenating version number components can lead to unexpected results, like 1.9 becomes "19" and 1.10 becomes "110" which would be numerically greater than 2.0 or "20".

**Comment by MagicAndre1981** [comment]
ok, I would pick revnum for the `android:versionCode`

**Comment by MagicAndre1981** [comment]
@ygoe 

any update?

**Comment by MagicAndre1981** [comment]
@ygoe 

any update on this?

**Comment by ygoe** [comment]
Closing because this probably isn't going to happen anymore. If more people are interested in this, please comment.

**Comment by MagicAndre1981** [comment]
>  If more people are interested in this, please comment.

I now use a workaround by changing the AndroidManifest.xml and Package.appxmanifest via PreBuildEvent for the csproj files. But I would still use 1 solution for all.
