### ISSUE TITLE
Replace/Remove invalid characters from branch name

### ISSUE THREAD

**Issue by AndreasAmMueller** [ygoe/NetRevisionTask#22]
It is possible to use characters in branch names, which are not allowed in package pre-release names.

e.g. to create branch trees you could use `feature/fancy_branch_name`.    
The characters `/` and `_` are not allowed.

Definition of allowed characters can be found here:    
[SemVer 2.0 Spec](https://semver.org/spec/v2.0.0.html#spec-item-9)

**Comment by ygoe** [comment]
Long fixed in #23.
