### ISSUE TITLE
Set the package version with the value of version instead of informational version

### ISSUE THREAD

**Issue by chucklu** [ygoe/NetRevisionTask#5]
According https://andrewlock.net/version-vs-versionsuffix-vs-packageversion-what-do-they-all-mean/

> PackageVersion is the only version number that isn't embedded in the output dll directly. Instead, it's used to control the version number of the NuGet package that's generated when you call dotnet pack.
> 
> **By default, PackageVersion takes the same value as Version**, so it's typically a three value SemVer version number, with or without a pre-release label. As with all the other version numbers, it can be overridden at build time, so it can differ from all the other assembly version numbers.

According https://github.com/NuGet/Home/issues/9560, net revision task set the package version
https://github.com/ygoe/NetRevisionTask/blob/c619ac946ccca1feeafb917596703ee8f08d697e/NetRevisionTask/build/Unclassified.NetRevisionTask.targets#L47

**Comment by ygoe** [comment]
I'll have to try this out and make some tests. This might take a few days (or longer).

Have you tried setting the `<PackageVersion>` element yourself in your project file?

**Comment by chucklu** [comment]
There is an article about this https://andrewlock.net/version-vs-versionsuffix-vs-packageversion-what-do-they-all-mean/
The author of SuperSocket might take a try

> if you're creating a NuGet package with dotnet pack, and you want to override the PackageVersion, you'll need to use MSBuild property overrides
> 
> dotnet pack --no-build /p:PackageVersion=9.9.9-beta

**Comment by ygoe** [comment]
I'm not sure I like this suggested change. It would by default never produce pre-release packages, even for pre-release code. It has proven useful to have pre-release packages so I'll probably just keep it that way. If you want another package version, you're free to define it in your project yourself. Please let me know if there's any issue doing that.

**Comment by chucklu** [comment]
@ygoe  Thanks for your reply, but now we have switched to use https://github.com/dotnet/Nerdbank.GitVersioning.
