### ISSUE TITLE
Revision ID Cannot be truncated to dotted-numeric

### ISSUE THREAD

**Issue by cpa-level-it** [ygoe/NetRevisionTask#7]
I sometimes have the following error message when I try to compile my application

`Revision ID cannot be truncated to dotted-numeric: 1362c129e0fc8604144d0c95cdb78b4ad7680236`

Here is what I have in my AssemblyInfo.cs file

``` csharp
[assembly: AssemblyInformationalVersion("{chash}")]
```

Most of the time it works, it only seems to crash with specific hash messages.
Any idea ?

**Comment by ygoe** [comment]
Yes, your format is not numeric. Use another format if you need it to be converted to the simpler version attributes. They require it. A hash is not usable for that.

For numeric formats, you could take a look at [SemVer](https://semver.org), for example.
