### ISSUE TITLE
When will this library support .net 4.7?

### ISSUE THREAD

**Issue by chucklu** [ygoe/NetRevisionTask#8]
I have read that this library should be used 

> Just install the NuGet package Unclassified.NetRevisionTask to your .NET Framework 4.6 or .NET Standard 1.6 project in VS 2015 or later and it starts working for you.

I tired it with a console application, and target to .net 4.7.2 and find the commit hash did not embed into product version.

**Comment by ygoe** [comment]
I haven't used old-style projects for a while and can't remember where I use NetRevisionTask in one of these projects, so I'll have to try this out.

But have you considered that you may need to edit your .csproj or AssemblyInfo.cs file to see any effect?

As it says it supports .NET Framework 4.6, I'd assume it's also working for 4.7 and 4.8.

**Comment by chucklu** [comment]
What did you mean about this?
>  edit your .csproj or AssemblyInfo.cs file

**Comment by ygoe** [comment]
For old-style projects (not .NET Core), you have to add placeholders to your version attributes. Otherwise, this program doesn't know what you want. See “Usage in C# source code” in the readme text on the front page.

**Comment by chucklu** [comment]
It's my mistake, I forget to add the project in to a git repository.
